[default_upgrade]
name = "Ammunition Factory"

[[default_upgrade.production_channels]]
power = 4
rate = 25
build_costs = [
    { material = "ConstructionMaterials", cost = 25 }
]
inputs = [
    { material = "ConstructionMaterials", value = 1 },
    { material = "HeavyExplosiveMaterials", value = 1 }
]
outputs = [
    { material = "Napalm", value = 1 }
]

[upgrades."Oil Reformer"]
name = "Oil Reformer"

[[upgrades."Oil Reformer".production_channels]]
power = 1
rate = 150
inputs = [
    { material = "Oil", value = 120 },
    { material = "Water", value = 30 }
]
outputs = [
    { material = "Petrol", value = 150 }
]
build_costs = [
    { material = "ConstructionMaterials", cost = 200 }
]